name: Canary Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publish-canary:
    name: Publish Canary
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: contains(github.actor, 'renovate') == false
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies using Yarn
        run: yarn install
      - name: Build
        run: yarn build
      - name: Release Canary
        id: canary
        uses: 'kamilkisiela/release-canary@master'
        if: github.repository == 'dotansimha/graphql-code-generator'
        with:
          npm-token: ${{ secrets.NODE_AUTH_TOKEN }}
          npm-script: 'release:canary'
      - name: Publish a message
        if: steps.canary.outputs.released
        uses: 'kamilkisiela/pr-comment@master'
        with:
          message: |
            The latest changes of this PR are available as alpha in npm: `${{ steps.canary.outputs.version }}`

            Quickly update your package.json by running:

                npx match-version @graphql-codegen ${{ steps.canary.outputs.version }}
          bot-token: ${{ secrets.GH_API_TOKEN }}
          bot: 'theguild-bot'
          github-token: ${{ secrets.GITHUB_TOKEN }}
