name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Testing on ${{matrix.os}} and Node ${{matrix.node_version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [10, 12, 13]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1
      - name: Use Node ${{matrix.node_version}}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}

      - name: Bob, check the repo
        id: bob
        uses: 'kamilkisiela/bob@master'
      - name: Bob, check Lint
        id: bob-lint
        uses: 'kamilkisiela/bob@master'
        with:
          command: lint
      - name: Bob, check Test
        id: bob-test
        uses: 'kamilkisiela/bob@master'
        with:
          command: test
      - name: Bob, check Build
        id: bob-build
        uses: 'kamilkisiela/bob@master'
        with:
          command: build

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        if: steps.bob.outputs.dirty == 'true'
      - name: Cache Yarn
        uses: actions/cache@v1
        if: steps.bob.outputs.dirty == 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Jest
        uses: actions/cache@v1
        if: steps.bob.outputs.dirty == 'true'
        with:
          path: .cache/jest
          key: ${{ runner.os }}-jest-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-jest-
      - name: Install Dependencies using Yarn
        run: yarn install
        if: steps.bob.outputs.dirty == 'true'
      - name: Lint
        run: yarn affected:lint
        if: steps.bob-lint.outputs.dirty == 'true'
      - name: Build
        run: yarn affected:build
        if: steps.bob-build.outputs.dirty == 'true'
      - name: Test
        run: yarn affected:test
        if: steps.bob-test.outputs.dirty == 'true'
        env:
          CI: true
      - name: Test dev-tests
        if: steps.bob-build.outputs.dirty == 'true'
        run: |
          yarn run affected:examples
          git diff --exit-code -- dev-test/

  publish-canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: '13.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies using Yarn
        run: yarn install && git checkout yarn.lock
      - name: Build
        run: yarn build
      - name: Release Canary
        id: canary
        uses: 'kamilkisiela/release-canary@master'
        if: github.repository == 'dotansimha/graphql-code-generator'
        with:
          npm-token: ${{ secrets.NODE_AUTH_TOKEN }}
          npm-script: 'ci:release:canary'
      - name: Publish a message
        if: steps.canary.outputs.released
        uses: 'kamilkisiela/pr-comment@master'
        with:
          message: |
            The latest changes of this PR are available as alpha in npm: `${{ steps.canary.outputs.version }}`

            Quickly update your package.json by running:

                npx match-version @graphql-codegen ${{ steps.canary.outputs.version }}

          bot-token: ${{ secrets.GH_API_TOKEN }}
          bot: 'theguild-bot'
          github-token: ${{ secrets.GITHUB_TOKEN }}
