name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  lint:
    name: Linting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-17-16-yarn-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-17-16-yarn-
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
  prettier-check:
    name: ðŸ§¹ Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-17-16-yarn-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-17-16-yarn-
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Prettier Check
        run: yarn prettier:check
  dev-tests:
    name: Validating dev-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        method:
          - 'cjs'
          - 'esm'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-17-16-yarn-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-17-16-yarn-
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          CI: true
      - name: Test dev-tests ${{matrix.method}}
        run: |
          yarn run generate:examples:${{matrix.method}}
          git diff --exit-code -- dev-test/
  esm:
    name: Testing exports integrity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-17-16-yarn-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-17-16-yarn-
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          CI: true
      - name: Test ESM & CJS integrity
        run: yarn bob check
  test:
    name: Unit Test on Node ${{matrix.node_version}} (${{matrix.os}}) and GraphQL v${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    needs:
      - lint
      - prettier-check
      - dev-tests
      - esm
    strategy:
      matrix:
        os: [ubuntu-latest] # remove windows to speed up the tests
        node_version: [12, 14, 16, 18]
        graphql_version: [15, 16, '17.0.0-alpha.1']
        include:
          - node-version: 12
            os: windows-latest
            graphql_version: 16
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}
      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-${{matrix.node_version}}-${{matrix.graphql_version}}-yarn-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-${{matrix.node_version}}-${{matrix.graphql_version}}-yarn-
      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
      - name: Install Dependencies
        run: yarn
      - name: Cache Jest
        uses: actions/cache@v3
        with:
          path: .cache/jest
          key: ${{runner.os}}-${{matrix.node_version}}-${{matrix.graphql_version}}-jest-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-${{matrix.node_version}}-${{matrix.graphql_version}}-jest-
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
        env:
          CI: true
